### PR TITLE
Support the system WIFI setting.

### PR DESCRIPTION
**Pull request by rootwhois**
Support the system WIFI setting, but it can't use HeliPort.

### CODE REVIEW

**Comment by rootwhois** [comment]
Testing on 7200U,  Mi-Air.

**Comment by johnnync13** [comment]
For the moment, I prefer not use https://github.com/usr-sse2/Black80211-Catalina.

**Comment by rootwhois** [comment]
OK, thanks for your hard working.

**Comment by stevezhengshiqi** [comment]
Actually, AirportItlwm is easier to use since it does not require a second kext. Black80211 requires a itlwm as the plugin.

**Pull request closed without merging**
