### PR TITLE
Fix that HIMI display cann't be woken up from screen off, sleep or power off #111

### PR DESCRIPTION
**Pull request by vimcaw**
Update WhateverGreen.kext to 1.3.8, and add boot argument "igfxagdc=0" can fix this.

Relative discusses:
* https://github.com/acidanthera/bugtracker/issues/783
* [关于更新macOS 10\.15\.4 以后出现的HDMI接口唤醒的问题跟进\-远景论坛\-微软极客社区](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1850890&highlight=HDMI)
* [WEG1\.38更新，解决笔记本10\.15\.4外接HDMI不能亮屏问题\-远景论坛\-微软极客社区](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1852184&highlight=HDMI)

### CODE REVIEW

**Comment by vimcaw** [comment]
After testing, it seems that it can wake up only when it boot, and it seems to not work after sleep.

**Comment by yllwfsh** [comment]
There's some changes to the OC config.plist other than the boot arg. I'll delete that file and add the boot argument manually, then merge it

**Comment by yllwfsh** [comment]
Done: https://github.com/johnnync13/Xiaomi-Mi-Air/commit/7792741e6a152760185e936a5d8158f54430745e

**Comment by vimcaw** [comment]
Yeah, I use `OpenCore Configurator` to add `boot args`, maybe it modified other position of the file.

**Comment by vimcaw** [comment]
In my case, `WhateverGreen.kext 1.3.8` and `igfxagdc=0` only fix HDMI wake from booting, it still doesn't be woken from sleep and shutdown screen, I will test other boot args when I'm free.


WhateverGreen.kext v1.3.8 Release Log: 

https://github.com/acidanthera/WhateverGreen/releases/tag/1.3.8

* Added igfxfw=2 boot argument and igfxfw IGPU property to load Apple GuC firmware
* Added igfxpavp=1 boot argument (and igfxpavp property) to force enable PAVP output
* Added igfxfcms=1 boot argument (and complete-modeset property) on Skylake and Apple
* Improved performance with Lilu 1.4.3 APIs
* Added -igfxfbdbg boot argument to debug IGPU framebuffer (debug builds only)
* Added igfxagdc=0 boot argument and disable-agdc IGPU property to disable AGDC
* Added igfxonln=1 boot argument and force-online IGPU property force online status for all displays
* Added igfxonlnfbs=MASK boot argument and force-online-framebuffers IGPU property to override display status

**Comment by vimcaw** [comment]
I have tested only an `igfxonln=1` arg, HIDM can't be woken up both from boot and sleep, but improved blinking when manually plugging and unplugging HDMI.

**Comment by yllwfsh** [comment]
> Yeah, I use `OpenCore Configurator` to add `boot args`, maybe it modified other position of the file.

Yeah Opencore Configurator doesn't always play nice with the config.plist and different versions of OpenCore. I always edit using a straight plist editor like ProperTree

**Comment by vimcaw** [comment]
> > Yeah, I use `OpenCore Configurator` to add `boot args`, maybe it modified other position of the file.
> 
> Yeah Opencore Configurator doesn't always play nice with the config.plist and different versions of OpenCore. I always edit using a straight plist editor like ProperTree

Thanks, I am still a rookie in the Hackintosh, it will be easier to use this tool. ☺️

**Comment by FuckDoctors** [comment]
mark~

**Comment by vimcaw** [comment]
I made #142 to fix this thoroughly.

**Comment by yllwfsh** [comment]
Released https://github.com/johnnync13/Xiaomi-Mi-Air/releases/tag/v7.5

**Pull request merged**
